management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

spring:
  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${APP_KAFKA_CONSUMER_GROUP_ID:market-state-service}

app:
  kafka:
    topic:
      depth-diff: ${APP_KAFKA_TOPIC_DEPTH_DIFF:canonical.market.depthdiff.v1}
